---

- name: install wordpress
  hosts: serverx
  gather_facts: false
  remote_user: root
  tasks:
   - name: ping
     ping:

   - name: yum install
     yum:
      name: "{{ item }}"
      state: latest
     loop:
      - httpd
      - mariadb
      - mariadb-server
      - php
      - php-common
      - php-mysql
      - php-gd
      - php-xml
      - php-mbstring
      - php-mcrypt
      - php-xmlrpc
      - unzip
      - wget
      - python-pip

   - name: start services
     service:
      name: "{{item}}"
      state: started
      enabled: yes
     loop:
      - httpd
      - mariadb

   - name: firewalld
     firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

   - name: install mysql
     pip:
      name: PyMySQL
      state: latest

   - name: set password for mysqladmin
     mysql_user:
      login_user: root
      login_password: abc
      name: root
      password: abc
      state: present

   - name: delete anonymous user
     mysql_user:
      login_user: root
      login_password: abc
      name: ''
      state: absent

   - name: secure root user
     mysql_user:
      login_user: root
      login_password: abc
      name: root
      password: abc
      host: $item 
     with_items:
      - localhost
      - 127.0.0.1
      - ::1

   - name: drop database test
     mysql_db:
      login_user: root
      login_password: abc
      name: test
      state: absent

   - name: delete database test
     shell: echo "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';" | mysql -uroot -p"abc"

   - name: create wordpress database
     mysql_db:
      login_user: root
      login_password: abc
      name: wordpress
      state: present

   - name: grant all privileges on wordpress
     mysql_user:
      login_user: root
      login_password: abc
      name: ansible
      password: mypassword
      priv: 'wordpress.*:ALL'

   - name: download wordpress.gz
     get_url:
      url: https://wordpress.org/wordpress-5.0.tar.gz
      dest: /tmp/wordpress-5.0.tar.gz

   - name: unarchive wordpress.gz
     unarchive:
      src: /tmp/wordpress-5.0.tar.gz
      dest: /var/www/html/
      remote_src: yes
   
   - name: chown apache:apache
     file:
      path: /var/www/html/wordpress
      owner: apache
      group: apache

   - name: chmod 755
     file:
      path: /var/www/html/wordpress
      mode: '755'

   - name: mkdir uploads
     file:
      path: /var/www/html/wordpress/wp-content/uploads
      state: directory
      group: apache

   - name: mv
     copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
      remote_src: yes

   - name: delete old file
     file:
      path: /var/www/html/wordpress/wp-config-sample.php
      state: absent

   - name: vim
     lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_NAME'
      line: define('DB_NAME', 'wordpress');

   - name: vim
     lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_USER'
      line: define('DB_USER', 'ansible');

   - name: vim
     lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_PASSWORD'
      line: define('DB_PASSWORD', 'mypassword');

   - name: vim
     lineinfile:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'DB_HOST'
      line: define('DB_NAME', 'localhost');

